# Generated by Django 5.2.12 on 2026-03-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='telemetryevent',
            new_name='telemetry_t_event_t_037514_idx',
            old_name='telemetry_telemetryevent_event_type_idx',
        ),
        migrations.RenameIndex(
            model_name='telemetryevent',
            new_name='telemetry_t_server__4277c1_idx',
            old_name='telemetry_telemetryevent_server_id_idx',
        ),
        migrations.RenameIndex(
            model_name='telemetryevent',
            new_name='telemetry_t_occurre_4a2615_idx',
            old_name='telemetry_telemetryevent_occurred_at_idx',
        ),
    ]
