# Generated by Django 5.2.12 on 2026-03-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='permission',
            new_name='permissions_group_d1224d_idx',
            old_name='permissions_permission_group_idx',
        ),
    ]
