# Generated by Django 5.2.12 on 2026-03-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voicechannel',
            new_name='voice_voice_server__117bf0_idx',
            old_name='voice_voicechannel_server_id_idx',
        ),
        migrations.RenameIndex(
            model_name='voicechannel',
            new_name='voice_voice_externa_148e54_idx',
            old_name='voice_voicechannel_external_id_idx',
        ),
        migrations.RenameIndex(
            model_name='voicechannel',
            new_name='voice_voice_name_e1524e_idx',
            old_name='voice_voicechannel_name_idx',
        ),
        migrations.RenameIndex(
            model_name='voicesession',
            new_name='voice_voice_server__ea5511_idx',
            old_name='voice_voicesession_server_id_idx',
        ),
        migrations.RenameIndex(
            model_name='voicesession',
            new_name='voice_voice_started_b2d813_idx',
            old_name='voice_voicesession_started_at_idx',
        ),
        migrations.RenameIndex(
            model_name='voicesession',
            new_name='voice_voice_ended_a_3aea31_idx',
            old_name='voice_voicesession_ended_at_idx',
        ),
    ]
