# Generated by Django 5.2.12 on 2026-03-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moderationaction',
            new_name='moderation__server__12801c_idx',
            old_name='moderation_moderationaction_server_id_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationaction',
            new_name='moderation__action__27908d_idx',
            old_name='moderation_moderationaction_action_type_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationaction',
            new_name='moderation__created_6378e6_idx',
            old_name='moderation_moderationaction_created_at_idx',
        ),
    ]
