# Generated by Django 5.2.12 on 2026-03-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='widgetdefinition',
            new_name='widgets_wid_widget__b9789f_idx',
            old_name='widgets_widgetdefinition_widget_type_idx',
        ),
    ]
